name: akademus_app
description: "App by Akademus GmbH"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  shared_preferences: ^2.5.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  meta: ^1.12.0
  flutter_math_fork: ^0.7.4
  flutter_markdown_plus: ^1.0.12
  markdown: ^7.3.1
  web: ^1.1.1
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/datenschutz.html
    - assets/images/
    - assets/flashcards/
    - assets/flashcards/analysis/
    - assets/flashcards/geometrie/
    - assets/flashcards/stochastik/
    - assets/flashcards_manifest.json
    - assets/quiz_manifest.json
